#!/usr/bin/env bash
# Build the macOS app bundle for Whisper Dictate.
#
#   ./build_macos_app.sh                    # builds dist/Whisper Dictate.app
#   ./build_macos_app.sh --install          # builds, then replaces /Applications/Whisper Dictate.app
#   ./build_macos_app.sh --login-item       # starts the installed app at login (LaunchAgent)
#   ./build_macos_app.sh --remove-login-item  # stops starting it at login
#
# The bundle is a thin launcher, not a frozen copy of the sources: its
# executable starts launcher.py from this checkout with the project's .venv -
# the same entry point run_mac.sh uses, so platform_mac.py (Tk/AppKit startup
# order, main-thread paste, Cmd+V via System Events, stale lock recovery) is
# always applied. Keeping the app up to date is therefore just install.py plus
# a rebuild; there is no second copy of the code that could go stale.
#
# The bundle is code-signed (an Apple Development / Distribution identity when
# one is installed, ad-hoc otherwise): macOS attaches the Microphone,
# Accessibility and Input Monitoring grants to the signed app identity, so
# rebuilding the app does not lose the permissions it was already given. The
# Info.plist carries the usage strings macOS requires for the Microphone and
# Automation (System Events) prompts.
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="Whisper Dictate"
BUNDLE_ID="com.beckerhub.whisperdictate"
APP="$BASE_DIR/dist/$APP_NAME.app"
CONTENTS="$APP/Contents"

if [ "$(uname -s)" != "Darwin" ]; then
    echo "build_macos_app.sh builds a macOS .app bundle - run it on macOS." >&2
    exit 2
fi

# --- options -----------------------------------------------------------------

OPT_INSTALL=0
OPT_LOGIN_ITEM=0
OPT_REMOVE_LOGIN_ITEM=0

for arg in "$@"; do
    case "$arg" in
        --install) OPT_INSTALL=1 ;;
        --login-item) OPT_LOGIN_ITEM=1 ;;
        --remove-login-item) OPT_REMOVE_LOGIN_ITEM=1 ;;
        *)
            echo "usage: build_macos_app.sh [--install] [--login-item] [--remove-login-item]" >&2
            exit 2
            ;;
    esac
done

# --- bundle skeleton ---------------------------------------------------------

rm -rf "$APP"
mkdir -p "$CONTENTS/MacOS" "$CONTENTS/Resources"

cat > "$CONTENTS/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIconFile</key>
    <string>appicon</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSMicrophoneUsageDescription</key>
    <string>Whisper Dictate records the microphone only while a dictation hotkey is held and transcribes it locally on this Mac.</string>
    <key>NSAppleEventsUsageDescription</key>
    <string>Whisper Dictate pastes the transcription at the cursor with Cmd+V through System Events.</string>
</dict>
</plist>
PLIST

# --- launcher ----------------------------------------------------------------
# Absolute paths on purpose: Finder starts the app with a minimal environment,
# so nothing may rely on PATH or the current working directory.
#
# The app is started *detached* and this script exits right away. macOS 26
# implements status items as FrontBoard scenes: when the process that creates
# the item is the one LaunchServices launched for the .app, the scene is never
# granted and the item stays parked off-screen (AX position (-1, 1100) instead
# of the menu bar). A process started outside that launch context - which is
# what detaching produces, and what running ./run_mac.sh by hand does - gets a
# normal menu-bar item, so the icon shows whether the app is opened from
# Finder, the Dock, or a terminal. This was reproduced with a minimal
# bash -> python bundle as well, so it is not specific to this app's code.

cat > "$CONTENTS/MacOS/$APP_NAME" <<LAUNCHER
#!/bin/bash
# Generated by build_macos_app.sh - do not edit the installed copy.

REPO="$BASE_DIR"
VENV_PY="\$REPO/.venv/bin/python"
LAUNCH_LOG="\$REPO/.app-launch.log"

if [ ! -d "\$REPO" ]; then
    /usr/bin/logger -t whisper-dictate "source checkout missing: \$REPO"
    exit 1
fi

cd "\$REPO"

# First start after a clean checkout: build the virtualenv (installs
# requirements.txt).
if [ ! -x "\$VENV_PY" ]; then
    /usr/bin/env python3 "\$REPO/install.py" --platform macos --no-doctor >>"\$LAUNCH_LOG" 2>&1
fi

# launcher.py applies the macOS platform patches (platform_mac.py) - starting
# main.py directly would skip them. Starting it while the app already runs is
# harmless: main.py's single-instance guard makes the second start exit.
nohup "\$VENV_PY" "\$REPO/launcher.py" </dev/null >>"\$LAUNCH_LOG" 2>&1 &
exit 0
LAUNCHER
chmod +x "$CONTENTS/MacOS/$APP_NAME"

# --- icon --------------------------------------------------------------------
# Rendered from icon.ico with the venv's Pillow, so the app icon always comes
# from the repository's own asset.

if [ -f "$BASE_DIR/icon.ico" ]; then
    ICONSET="$(mktemp -d)/appicon.iconset"
    mkdir -p "$ICONSET"
    if "$BASE_DIR/.venv/bin/python" - "$BASE_DIR/icon.ico" "$ICONSET" <<'PY'
import sys

from PIL import Image

source, out = sys.argv[1], sys.argv[2]
image = Image.open(source)
image.load()
for size in (16, 32, 64, 128, 256):
    image.resize((size, size), Image.LANCZOS).save(f"{out}/icon_{size}x{size}.png")
    if size <= 128:
        image.resize((size * 2, size * 2), Image.LANCZOS).save(
            f"{out}/icon_{size}x{size}@2x.png"
        )
PY
    then
        iconutil -c icns -o "$CONTENTS/Resources/appicon.icns" "$ICONSET"
    else
        echo "warning: icon.ico could not be rendered, bundling without an icon" >&2
    fi
    rm -rf "${ICONSET%/*}"
fi

# --- validate and sign -------------------------------------------------------

plutil -lint "$CONTENTS/Info.plist" >/dev/null

IDENTITY="$(security find-identity -v -p codesigning 2>/dev/null \
    | grep -E '"(Apple Development|Apple Distribution|Developer ID Application)' \
    | sed -E 's/.*"([^"]*)".*/\1/' \
    | head -1 || true)"

if [ -n "$IDENTITY" ]; then
    echo "Signing with the $IDENTITY identity"
    codesign --force --identifier "$BUNDLE_ID" --sign "$IDENTITY" "$APP"
else
    echo "No code-signing identity found - signing ad-hoc"
    codesign --force --identifier "$BUNDLE_ID" --sign - "$APP"
fi
codesign --verify "$APP"

# --- optional install --------------------------------------------------------

if [ "$OPT_INSTALL" = "1" ]; then
    TARGET="/Applications/$APP_NAME.app"
    echo "Installing into $TARGET"
    rm -rf "$TARGET"
    ditto "$APP" "$TARGET"
    codesign --verify "$TARGET"
fi

# --- login item --------------------------------------------------------------
# A LaunchAgent in the user's GUI session opens the installed app at login -
# the same as double-clicking it, so the app does not depend on being started
# by this script. RunAtLoad starts it once; there is no KeepAlive, so quitting
# from the menu bar stays quit until the next login. Using `open -g` keeps the
# login from stealing focus (the app is an agent without a Dock icon anyway).
#
# The stdio paths live in ~/Library/Logs, not in the repo: launchd opens them
# before it starts the job, and a path inside ~/Documents fails with exit code
# 78 (EX_CONFIG) because that folder is TCC-protected. launchd creates the log
# file but not its directory, so only an existing directory may be used.

AGENT_LABEL="$BUNDLE_ID"
AGENT_PLIST="$HOME/Library/LaunchAgents/$AGENT_LABEL.plist"
AGENT_LOG="$HOME/Library/Logs/whisper-dictate-launch.log"

if [ "$OPT_REMOVE_LOGIN_ITEM" = "1" ]; then
    launchctl bootout "gui/$(id -u)/$AGENT_LABEL" 2>/dev/null || true
    rm -f "$AGENT_PLIST"
    echo "Login item removed: $AGENT_PLIST"
fi

if [ "$OPT_LOGIN_ITEM" = "1" ]; then
    if [ ! -d "/Applications/$APP_NAME.app" ]; then
        echo "--login-item needs the app in /Applications; run --install first." >&2
        exit 2
    fi
    mkdir -p "$HOME/Library/LaunchAgents"
    cat > "$AGENT_PLIST" <<AGENT
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$AGENT_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/open</string>
        <string>-g</string>
        <string>-a</string>
        <string>/Applications/$APP_NAME.app</string>
    </array>
    <key>LimitLoadToSessionType</key>
    <string>Aqua</string>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$AGENT_LOG</string>
    <key>StandardErrorPath</key>
    <string>$AGENT_LOG</string>
</dict>
</plist>
AGENT
    plutil -lint "$AGENT_PLIST" >/dev/null
    launchctl bootout "gui/$(id -u)/$AGENT_LABEL" 2>/dev/null || true
    launchctl bootstrap "gui/$(id -u)" "$AGENT_PLIST"
    echo "Login item installed: $AGENT_PLIST"
    echo "Login item log:       $AGENT_LOG"
fi

echo
echo "Built: $APP"
if [ "$OPT_INSTALL" = "1" ]; then
    echo "Launch:  open \"/Applications/$APP_NAME.app\""
else
    echo "Install: ./build_macos_app.sh --install"
fi
